#!/bin/sh

__cleanup()
{
	SIGNAL=$1

	if [ -n "$SIGNAL" ]
	then
		trap $SIGNAL
		kill -${SIGNAL} $$
	fi
}

__message()
{
	echo
	echo "Usage:"
	echo " $0 <key> <user> <runner-name> <github> <labels> <token>"
	echo ""
	echo "Copy configuration into the virtual machine using a private key."
	echo
	echo "Options:"
	echo " -k, --key                    private key to use"
	echo " -u, --user                   user account to log into"
	echo " -r, --runner-name            github action runner"
	echo " -g, --github                 github repository url"
	echo " -l, --labels                 comma separated string with labels"
	echo " -t, --token                  github token for runner"
	echo
	echo " -h, --help                   display this help"
	echo
	echo "For more details see https://github.com/mrquincle/autorun_github_runner."
}

trap __message EXIT

# Requires GNU getopt. If long options are required, install it on OS X and FreeBSD.
OPTS=$(getopt --options k:u:r:g:l:t:h \
	--long key:,user:,runner-name:,github:,labels:,token:,help \
	--name "$0" -- "$@")

# If previous command returns non-zero exit code, something went wrong
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$OPTS"

while true; do
	case "$1" in
		-k | --key )
			key="$2"
			shift 2
			;;
		-u | --user )
			user="$2"
			shift 2
			;;
		-r | --runner-name )
			runner_name="$2"
			shift 2
			;;
		-g | --github )
			github="$2"
			shift 2
			;;
		-l | --labels )
			labels="$2"
			shift 2
			;;
		-t | --token )
			token="$2"
			shift 2
			;;
		-h | --help)
			exit 0
			;;
		-- )
			shift
			;;
		* )
			break;
			;;
	esac
done

if [ -z "$key" ] || [ -z "$user" ] || [ -z "$runner_name" ] || [ -z "$github" ] || [ -z "$labels" ] || [ -z "$token" ]; then
	echo "Not enough arguments"
	exit
fi

trap __cleanup EXIT

dockerfile=custom/.docker-compose.yml.private
echo "Create private file: $dockerfile"
cp custom/docker-compose.yml "$dockerfile"

sed -i "s|@@RUNNER_NAME@@|$runner_name|g" "$dockerfile"
sed -i "s|@@RUNNER_REPOSITORY@@|$github|g" "$dockerfile"
sed -i "s|@@RUNNER_LABELS@@|$labels|g" "$dockerfile"
sed -i "s|@@RUNNER_TOKEN@@|$token|g" "$dockerfile"

echo "Copy all files in ./custom to virtual machine"
rsync -avzul -e "ssh -i $key -p 2222" ./custom $user@localhost:~

